#!/bin/bash
source ./local_config/env.sh
echo "Entering a New $APP Container for $USER. Exit will destroy Container."

case "$1" in
        dreg)
          echo "Run DREG Image"
          IM="$DREG/$USER/$APP"
            ;;
        *)
          echo "Run Local Image"
          IM="$USER/$APP"
            ;;
esac

docker run \
  --rm \
  -it \
  -e USER=$(cat ./local_config/secure/user.txt 2>/dev/null) \
  -e PASS=$(cat ./local_config/secure/password.txt 2>/dev/null) \
  -e SLEEP=60 \
  --volume $PWD/var/tmp:/opt/$APP/tmp/  \
  --volume $PWD/var/log:/opt/$APP/log/  \
  --dns 10.20.32.7 \
  --hostname $APP \
  $IM bash --login
